### ISSUE TITLE
Extend lambda interfaces to rethrow DemotedExceptions

### ISSUE THREAD

**Issue by ecksteinmitre** [mitre-public/commons#13]
When writing with java streams, often one encounters a map/filter operation that contains a call to a function that throws a checked exception.  The standard way to handle this in a lambda is to wrap the call in a try/catch, e.g.:
```java
List<Path> pathList;
List<String> fileContents = pathList.stream()
    .map(path -> {
      try {
        return Files.readString(path);
      } catch (IOException e) {
        throw DemotedException.demote(e);
      }
    })
    .filter(Objects::nonNull)
    .toList();
```

However, this can have a big impact on readability (especially with a longer stream chain).  Instead, (some?) of the lambda interfaces can be extended similar to:
```java
@FunctionalInterface
public interface CheckedFunction<S, T> {
  T apply(S t) throws Exception;

  public static <S, T> Function<S, T> demote(CheckedFunction<S, T> func) {
    return x -> {
      try {
        return func.apply(x);
      } catch (Exception e) {
        throw DemotedException.demote(e);
      }
    };
  }
}
```

then the stream can be refactored to:
```java
List<String> fileContents = pathList.stream()
    .map(CheckedFunction.demote(path -> Files.readString(path)))
    .filter(Objects::nonNull)
    .toList();
```

**Comment by ecksteinmitre** [comment]
a few similar options available, e.g. apache commons has a[FailableStream](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/Streams.FailableStream.html)

**Comment by politeRaccoon** [comment]
As discussed yesterday -- awesome addition.
