### ISSUE TITLE
Can't build project outside of MITRE network

### ISSUE THREAD

**Issue by yossarian1988** [mitre-public/commons#2]
Is the idea that folks should just fork this repo for use? Or will it eventually point to Maven central (not proxy)?

https://github.com/mitre-public/commons/blob/main/build.gradle.kts#L11

**Comment by politeRaccoon** [comment]
Apologies for the delay, this is the first time I'm seeing this message just now.

This will eventually be published to maven central.   But before "maven central publishing" is up and running you may have to build locally.  But building locally is an ugly stop-gap solution that shouldn't be the long-term solution

**Comment by politeRaccoon** [comment]
Fix is in PR

**Comment by politeRaccoon** [comment]
Maven Central is on the way

**Comment by yossarian1988** [comment]
Thanks, @politeRaccoon
